server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop



