spring:
  datasource:
    bank:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:23306/bank
      username: root
      password: root
    user:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:23307/bank_user
      username: root
      password: root
    coupon1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13307/coupon1
      username: root
      password: root
    coupon2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:13308/coupon2
      username: root
      password: root
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:23306/bank
    user: root
    password: root
  data:
    redis:
      host: localhost
      port: 26379
      timeout: 3000 #ms
  kafka:
    template:
      default-topic: traffic-bank
    consumer:
      bootstrap-servers: localhost:29092
      group-id: bank-api
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1000
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

topics:
  transaction: traffic-bank

logging:
  level:
    root: info
    org:
      apache:
        kafka: info
