server:
  port: 7777
  servlet:
    session:
      timeout: 30m

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    throw-exception-if-no-handler-found: true
  jmx:
    enabled: true

