spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/bank
    username: root
    password: root
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:23306/bank
    user: root
    password: root

logging:
  level:
    root: debug
