version: '3'
services:
  mysql-traffic-bank:
    image: mysql:8.0
    container_name: mysql-traffic-bank
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - traffic-bank-mysql-volume:/var/lib/mysql
  redis-traffic-bank:
    image: redis:7.0
    container_name: redis-traffic-bank
    ports:
      - "26379:6379"
    volumes:
      - traffic-bank-redis-volume:/usr/local/etc/redis

volumes:
  traffic-bank-mysql-volume:
    driver: local
  traffic-bank-redis-volume:
    driver: local
